[server]
headless = true
port = 8501
enableCORS = false

[browser]
serverAddress = ""

[theme]
base = "dark"
primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#fafafa"
font = "sans serif"
